export const CHOMSKY_DATA = [
    {
      type: 'TYPE 0',
      name: 'Unrestricted',
      language: 'Recursively Enumerable',
      desc: 'The most general class of grammars. No restrictions on production rules. Can simulate any computational process.',
      automaton: 'Turing Machine',
      rule: 'X \\rightarrow Y',
      ruleX: 'X \\in (V \\cup \\Sigma)^* V (V \\cup \\Sigma)^* \\text{ (X has } \\ge 1 \\text{ non-terminal)}',
      ruleY: 'Y \\in (V \\cup \\Sigma)^*',
      color: 'slate',
      borderColor: 'border-slate-500/30',
      textColor: 'text-slate-400',
      accentColor: 'bg-slate-500/10',
      iconColor: 'text-slate-400',
      glow: 'shadow-[0_0_50px_rgba(148,163,184,0.1)]'
    },
    {
      type: 'TYPE 1',
      name: 'Context-Sensitive',
      language: 'CSLs',
      desc: 'Rules are dependent on surrounding context. The length of the string never decreases during derivation.',
      automaton: 'LBA',
      rule: 'X \\rightarrow Y',
      ruleX: 'X \\in (V \\cup \\Sigma)^* V (V \\cup \\Sigma)^*',
      ruleY: 'Y \\in (V \\cup \\Sigma)^* \\text{ and } |Y| \\ge |X| \\text{ (length does not decrease)}',
      color: 'purple',
      borderColor: 'border-purple-500/30',
      textColor: 'text-purple-400',
      accentColor: 'bg-purple-500/10',
      iconColor: 'text-purple-400',
      glow: 'shadow-[0_0_50px_rgba(168,85,247,0.1)]'
    },
    {
      type: 'TYPE 2',
      name: 'Context-Free',
      language: 'CFLs',
      desc: 'LHS is exactly one non-terminal variable. Replacement is independent of the surrounding symbols.',
      automaton: 'PDA',
      rule: 'X \\rightarrow Y',
      ruleX: 'X \\in V \\text{ (exactly 1 non-terminal)}',
      ruleY: 'Y \\in (V \\cup \\Sigma)^*',
      color: 'cyan',
      borderColor: 'border-cyan-500/30',
      textColor: 'text-cyan-400',
      accentColor: 'bg-cyan-500/10',
      iconColor: 'text-cyan-400',
      glow: 'shadow-[0_0_50px_rgba(34,211,238,0.1)]'
    },
    {
      type: 'TYPE 3',
      name: 'Regular',
      language: 'Regular Languages',
      desc: 'The simplest class of grammars. Used for lexical analysis and pattern matching in strings.',
      automaton: 'DFA / NFA',
      rule: 'X \\rightarrow Y',
      ruleX: 'X \\in V \\text{ (exactly 1 non-terminal)}',
      ruleY: '\\text{Right-Linear: } Y \\in \\{aT, a, \\epsilon\\}, \\text{ Left-Linear: } Y \\in \\{Ta, a, \\epsilon\\}',
      color: 'emerald',
      borderColor: 'border-emerald-500/30',
      textColor: 'text-emerald-400',
      accentColor: 'bg-emerald-500/10',
      iconColor: 'text-emerald-400',
      glow: 'shadow-[0_0_50px_rgba(16,185,129,0.1)]'
    }
  ];

export const GRAMMAR_EXAMPLES_LIST = [
  { name: "Balanced", grammar: "S -> ( S ) | S S | ε", target: "( ( ) ( ) )", desc: "Generates strings of balanced parentheses, e.g., (()) or ()()." },
  { name: "Left Recursion", grammar: "A -> A a | a", target: "aaa", desc: "A grammar is left-recursive if a non-terminal can derive a string that starts with itself (e.g., A → A a). This causes top-down parsers to enter infinite loops. Example: Generating 'aaa' by expanding A → Aa → Aaa → aaa." },
  { name: "Right Recursion", grammar: "A -> a A | a", target: "aaa", desc: "A grammar is right-recursive if a non-terminal derives a string that ends with itself (e.g., A → a A). This is generally safe for top-down parsers but can cause deep call stacks. Example: Generating 'aaa' by expanding A → aA → aaA → aaa." },
  { name: "Palindrome", grammar: "S -> a S a | b S b | a | b | ε", target: "aba", desc: "Generates symmetric strings like 'aba' or 'abba'." },
  { name: "aⁿbⁿ", grammar: "S -> a S b | ε", target: "aabb", desc: "Generates strings with equal 'a's then 'b's, e.g., 'aaabbb'." },
  { name: "aⁿb²ⁿ", grammar: "S -> a S bb | ε", target: "aabbbb", desc: "Generates strings with 'n' a's followed by '2n' b's, e.g., 'aabbbb'." },
  { name: "Ambiguous Expr", grammar: "E -> E + E | E * E | ( E ) | a", target: "a+a*a", desc: "Arithmetic expressions where 'a+a*a' has multiple parse trees." },
  { name: "Dangling Else", grammar: "S -> i t S e S | i t S | a", target: "i t i t a e a", desc: "Models the classic 'dangling else' ambiguity in programming." },
  { name: "Dyck Words", grammar: "S -> [ S ] | ( S ) | S S | ε", target: "[ ( ) ]", desc: "Strings with multiple types of balanced brackets, e.g., '[()]'." },
  { name: "Even Length", grammar: "S -> aa S | bb S | ab S | ba S | ε", target: "abba", desc: "Generates any string of even length over {a,b}." },
  { name: "Binary Nums", grammar: "S -> S 0 | S 1 | 0 | 1", target: "101", desc: "Generates all possible binary numbers." },
  { name: "ε-rules", grammar: "S -> A B\nA -> a | ε\nB -> b | ε", target: "ab", desc: "Demonstrates epsilon productions, generating 'a', 'b', 'ab', or 'ε'." },
];
